# Generated by Django 4.1.4 on 2023-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(blank=True, default='text', max_length=128, null=True, verbose_name='言語'),
        ),
    ]
