# Generated by Django 4.1.5 on 2023-01-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_tag_snippet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='snippets.tag', verbose_name='タグ'),
        ),
    ]
