# Generated by Django 4.1.5 on 2023-01-08 05:53

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('snippets', '0011_alter_snippet_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ'),
        ),
    ]
